environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: PowerShellCore
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: WindowsPowerShell
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    PowerShellEdition: PowerShellCore

build_script:
  - pwsh: ./tst/test.ps1 -CIBuild